### ISSUE TITLE
[infra/ci-test] Github Actions를 이용한 CICD 워크 플로우 작성

### ISSUE THREAD

**Issue by dldmsql** [MYONGSIK/Server#34]
## Description
Github Actions를 이용한 CI 워크 플로우와 CD 워크 플로우 작성

## To-do
- [x] 테스트를 위한 application-secret.yml 생성
- [x] Github Actions를 이용한 CI 워크 플로우 파일 생성
- [x] 테스트 코드를 통한 테스트
- [x] CD 워크 플로우 파일 생성 및 테스트

**Comment by dldmsql** [comment]
@Qbeom0925 성공하는 케이스와 실패하는 케이스의 테스트코드 작성을 통해 CI 워크 플로우 테스트를 진행했습니다.

**Comment by dldmsql** [comment]
[깃헙 액션으로 CI 테스트하기](https://devs0n.tistory.com/25) 블로그를 참고해서 진행했습니다.

**Comment by dldmsql** [comment]
CD 워크플로우 테스트 중에 마주한 이슈 -> github actions에 로그인된 docker hub 정보와 EC2에 로그인된 정보가 달라 ( 패스워드 변경에 따른 ) 오류 발생

[여기](https://m.blog.naver.com/wideeyed/221533279838) 참고
