### ISSUE TITLE
[feature/meal-evaluate] 식단 좋아요/싫어요 평가 기능 구현

### ISSUE THREAD

**Issue by Qbeom0925** [MYONGSIK/Server#55]
## Description
식단 좋아요/싫어요 평가 기능 구현
하나의 api에서 진행된다.

## To-do
- [x] 하나의 api에서 진행되는가?
- [x] 연산이 이루어 지는가?
- [x] 선택한 식단에 대해서 DB 반영이 이루어 지는가?
