### ISSUE TITLE
[infra/mongodb] RDB에서 MongoDB로 마이그레이션 로컬 환경 구축

### ISSUE THREAD

**Issue by dldmsql** [MYONGSIK/Server#80]
## Description
잦은 요구사항 변경에 따른 테이블 변경으로 RDB에서 MongoDB(NoSQL)로 마이그레이션 도입을 고려 중입니다. 로컬 환경에서 ( 도커 컨테이너 환경 이용 ) 우선적으로 테스트 진행 후, 이슈가 없음이 보장되면 운영환경에 적용할 계획입니다.

## To-do
- [x] MongoDB 세팅 ( 도커 컨테이너, 프로퍼티 설정 )
- [x] 식단 조회 기능에 한해 우선적으로 마이그레이션 진행
- [x] 테스트 코드 작성

## ETC
이슈 발생 시, 마이그레이션은 진행하지 않겠습니다.
